@extends('layouts.app') {{-- Assuming you have a main layout --}}

@section('content')
<div class="bg-gray-50 min-h-screen py-12">
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            
            <div class="px-6 py-8 border-b border-gray-200 bg-indigo-700">
                <h1 class="text-3xl font-bold text-white">Terms and Conditions of Membership</h1>
                <p class="mt-2 text-indigo-100">Last Updated: Decemeber 25, 2025</p>
            </div>

            <div class="px-6 py-8 text-gray-700 leading-relaxed space-y-8">
                
                <section>
                    <p class="text-lg">Welcome to <strong>MD Matrimony</strong> (hereinafter referred to as "MDM").</p>
                    <p class="mt-4 bg-blue-50 p-4 border-l-4 border-blue-400 italic">
                        This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                    </p>
                    <p class="mt-4">
                        "MDM Services" means the matrimonial service provided by <strong>MD Matrimony Services</strong> (MSME Registered, UDYAM: UDYAM-UP-32-0098296), having its registered office at <strong>Office No 7, Chaturvedi Complex, Betiyahata Road, Gorakhpur - 273001</strong>.
                    </p>
                </section>

                <hr>

                <section>
                    <h2 class="text-xl font-bold text-gray-900 mb-4">1. Eligibility</h2>
                    <ul class="list-disc pl-6 space-y-2">
                        <li>Indian Citizens, Persons of Indian Origin (PIO), Non-Resident Indians (NRI), or persons of Indian Descent/Heritage.</li>
                        <li>Persons who intend to marry persons of Indian Origin.</li>
                        <li><strong>Age:</strong> 18 years or above (Women) or 21 years or above (Men).</li>
                        <li>If you have applied for divorce, you may register by stating "Awaiting Divorce".</li>
                    </ul>
                </section>

                <section>
                    <h2 class="text-xl font-bold text-gray-900 mb-4">2. Registration</h2>
                    <ul class="list-disc pl-6 space-y-2">
                        <li>You agree to provide true, accurate, and current information.</li>
                        <li><strong>Duplicate Profiles:</strong> Registration of duplicate profiles is not permitted. MDM reserves the right to suspend such profiles without notice.</li>
                        <li><strong>Commercial Use:</strong> Organizations or businesses cannot become members. The service is strictly for individual members with the bonafide intention of marriage.</li>
                    </ul>
                </section>

                <div class="grid md:grid-cols-2 gap-6">
                    <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                        <h3 class="font-bold text-gray-900 mb-2">4. Role of MDM</h3>
                        <p class="text-sm">MDM acts as an "Intermediary." We provide an interface but do not authenticate or endorse profile information. Verification is the user's responsibility.</p>
                    </div>
                    <div class="bg-gray-50 p-4 rounded-lg border border-gray-200">
                        <h3 class="font-bold text-gray-900 mb-2">5. Member Responsibility</h3>
                        <p class="text-sm">Members must verify credentials, provide recent photos, and disclose health records. Financial transactions between members are strictly prohibited.</p>
                    </div>
                </div>

                <section class="bg-indigo-50 p-6 rounded-xl border border-indigo-100">
                    <h2 class="text-xl font-bold text-indigo-900 mb-4">8. Grievance Officer</h2>
                    <table class="w-full text-sm">
                        <tr>
                            <td class="font-semibold py-1 w-32">Name:</td>
                            <td>RAM ASHISH YADAV</td>
                        </tr>
                        <tr>
                            <td class="font-semibold py-1">Email:</td>
                            <td class="text-indigo-600">grievance@mdmatrimony.com</td>
                        </tr>
                        <tr>
                            <td class="font-semibold py-1">Hours:</td>
                            <td>11 am to 6 pm IST (Mon-Sat)</td>
                        </tr>
                    </table>
                </section>

                <section>
                    <h2 class="text-xl font-bold text-gray-900 mb-4">11. Jurisdiction</h2>
                    <p>All disputes shall be subject to the exclusive jurisdiction of the courts in <strong>Gorakhpur, Uttar Pradesh, India</strong>.</p>
                </section>

                <div class="mt-10 pt-6 border-t border-gray-200 text-center text-sm text-gray-500">
                    &copy; {{ date('Y') }} MD Matrimony Services. All Rights Reserved.
                </div>
            </div>
        </div>
    </div>
</div>
@endsection